from enum import Enum


class ErrorCode(str, Enum):
    INVALID_SMILES = "INVALID_SMILES"
    COMPOUND_NOT_FOUND = "COMPOUND_NOT_FOUND"
    EMPTY_INGREDIENTS = "EMPTY_INGREDIENTS"
    ALL_UNRESOLVED = "ALL_UNRESOLVED"
    RDKIT_ERROR = "RDKIT_ERROR"
    BATCH_FILE_INVALID = "BATCH_FILE_INVALID"
    BATCH_FILE_TOO_LARGE = "BATCH_FILE_TOO_LARGE"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_NOT_COMPLETED = "JOB_NOT_COMPLETED"
    RATE_LIMITED = "RATE_LIMITED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
